spring:
 datasource:
   url: jdbc:mysql://192.168.2.147:3306/estacionamiento?useSSL=false
   username: ceibaadn
   password: ceibaadn
 jpa:
   show-sql: false
   hibernate:
     ddl-auto: update
   properties:
     hibernate:
       dialect: org.hibernate.dialect.MySQL5InnoDBDialect
       
   database-platform: org.hibernate.dialect.MySQL5InnoDBDialect